/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    ContactForm: typeof import('./components/ui/ContactForm.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FooterSection: typeof import('./components/FooterSection.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    Loading: typeof import('./components/ui/Loading.vue')['default']
    Modal: typeof import('./components/ui/Modal.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    ProjectCard: typeof import('./components/ui/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
